# GR Atom: Embedded Database Application
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-DATA-EMBDATAPP-001"
  name: "Embedded Database Application"
  normalized_name: "embedded_database_application"
  aliases:
    - "Embedded DB App"
    - "In-Process Database"
    - "Application-Embedded Database"
    - "Local Database Application"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - DATABASE
    - SQLITE
    - COLLECT
    - CRED

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L7"
  zone: "Z2"
  function: "D1.3"

# ==== Section 5: Definition ====
definition:
  what: >-
    An Embedded Database Application is a software application that integrates a database engine
    directly within its own process, eliminating the need for a separate database server. The
    database runs in-process as a library linked into the application rather than as an
    independent service. Common embedded database engines include SQLite, H2 Database, Berkeley
    DB, LevelDB, RocksDB, and Apache Derby. Embedded databases are used in web browsers
    (SQLite in Chrome, Firefox), mobile applications (SQLite on iOS/Android), desktop
    applications, IoT devices, and as local data stores within larger systems.
  why: >-
    Embedded database applications are security-relevant because they store data locally without
    the network-based security controls of client-server databases. Sensitive data stored in
    embedded databases (browser history, cookies, credentials, application settings) is
    accessible to any process with file system access to the database file. Adversaries
    frequently target embedded databases like browser SQLite stores and application credential
    databases for credential harvesting, sensitive data collection, and reconnaissance.
    The lack of network authentication means file system permissions are the primary
    access control mechanism.
  how: >-
    Embedded databases operate as libraries loaded into the application's memory space. The
    application opens a database file on the local file system and interacts with it through
    an API rather than a network protocol. Data is read from and written to files on disk
    using the database engine's storage format. Concurrency is managed through file-level
    or page-level locking. Encryption at rest may be supported through extensions (SQLCipher
    for SQLite) or application-level encryption. Access control depends entirely on file
    system permissions and application-level authorization, as there is no separate
    authentication layer.
  core_concepts:
    - key: "In-Process Operation"
      value: >-
        Embedded databases run within the application's memory space as a linked library,
        eliminating network overhead but also eliminating network-based security controls
        like authentication and encryption in transit.
    - key: "File-Based Access Control"
      value: >-
        Security depends on file system permissions to the database file, making any process
        or user with file access able to read or modify the database contents directly.
    - key: "Credential Harvesting Target"
      value: >-
        Browser and application embedded databases storing credentials, session tokens, and
        sensitive user data are primary targets for credential access techniques and data
        collection by adversaries.

# ==== Section 6: Relations ====
relations:
  - type: "is_a"
    target: "INFRA-DATA-DATAAPPL-001"
    description: "An embedded database application is a type of database application with an integrated in-process database engine"
  - type: "is_a"
    target: "INFRA-DATA-DATASTOR-001"
    description: "An embedded database application is a type of data store using local file-based persistence"

# ==== Section 7: Security Profile (optional) ====
security_profile:
  mitre_mapping:
    technique_id: "T1555.003"
    tactic:
      - "Credential Access"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  version: "1.0"
  confidence: "medium"
  trust_source: "derived"
  sources:
    - "SQLite documentation. https://www.sqlite.org/docs.html"
    - "MITRE ATT&CK T1555.003 - Credentials from Web Browsers."
    - "CWE-311: Missing Encryption of Sensitive Data."
  search_keywords:
    - "embedded database"
    - "SQLite"
    - "in-process database"
    - "embedded database security"
    - "browser database"
    - "local database"
    - "credential database"
    - "application database file"
  embedding_text: >-
    An Embedded Database Application integrates a database engine directly within its own process
    as a linked library, eliminating the need for a separate server. Common engines include
    SQLite, H2, Berkeley DB, LevelDB, and RocksDB. Embedded databases are used in browsers
    (Chrome, Firefox), mobile apps (iOS, Android), desktop applications, and IoT devices.
    Security concerns center on local data accessibility: any process with file system access
    can read or modify the database file. Adversaries frequently target embedded databases for
    credential harvesting (browser SQLite stores, application credential databases) and
    sensitive data collection (MITRE ATT&CK T1555.003). The lack of network authentication
    means file system permissions are the primary access control. Encryption at rest through
    extensions like SQLCipher provides additional protection but is not enabled by default.
