# GR Atom: NetWeaver
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-NETWEAVER-001"
  name: "NetWeaver"
  normalized_name: "netweaver"
  aliases:
    - "SAP NetWeaver"
    - "SAP NetWeaver Application Server"
    - "SAP NW"
    - "SAP Web Application Server"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WEB
    - HTTP
    - CONFIG
    - EXEC
    - DESER

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L6"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    SAP NetWeaver is a technology platform and application server that serves as the foundation
    for SAP enterprise applications including SAP ERP, S/4HANA, and SAP Business Suite. It
    provides ABAP and Java application server stacks, web services (ICF/ICM), portal services,
    process integration (PI/PO), and identity management. NetWeaver includes the SAP Internet
    Communication Manager (ICM) for HTTP processing and the SAP Message Server for internal
    communication between application instances.
  why: >-
    SAP NetWeaver is a high-value target due to its role as the foundation for critical
    enterprise business systems containing financial, HR, and operational data. Critical
    vulnerabilities have included CVE-2020-6287 (RECON - unauthenticated admin account creation),
    CVE-2022-22536 (ICM memory corruption), and CVE-2023-40309 (authorization bypass). The
    CISA has issued multiple alerts for SAP NetWeaver exploitation. Attackers target NetWeaver
    for access to SAP systems containing sensitive business data, financial transactions, and
    supply chain operations. Default configurations and exposed administrative interfaces
    (SAP Management Console, ICM admin) create additional risk.
  how: >-
    SAP NetWeaver processes HTTP requests through the Internet Communication Manager (ICM),
    routing them to the ABAP or Java application stacks. The SAP Message Server (port 3900)
    handles internal routing between application instances. Exploitation targets include the
    ICM HTTP parser for memory corruption, the LM Configuration Wizard for unauthenticated
    access (RECON vulnerability), deserialization flaws in the Java stack, and SSRF through
    SAP proxy services. The SAP Gateway (RFC protocol) enables remote function calls that
    attackers exploit for lateral movement within SAP landscapes. Misconfigured ACLs on the
    Message Server allow unauthorized registration of application instances.
  core_concepts:
    - key: "SAP Enterprise Platform"
      value: "Foundation technology platform for SAP enterprise applications processing critical business data including financials, HR, and supply chain operations"
    - key: "Critical Infrastructure Vulnerabilities"
      value: "High-severity vulnerabilities (RECON CVE-2020-6287, ICM CVE-2022-22536) enable unauthenticated remote access to SAP systems with CISA alerts"
    - key: "Complex Attack Surface"
      value: "Multiple service interfaces (ICM, Message Server, Gateway, Java stack) create a broad attack surface with HTTP parsing, deserialization, and RFC protocol vectors"

# ==== Section 6: Relations ====
relations:
  - type: "is_a"
    target: "INFRA-APP-ENTESERV-001"
    description: "SAP NetWeaver is an enterprise application server platform providing the runtime environment for SAP business applications"
  - type: "enables"
    target: "INFRA-APP-ENTEAPPS-001"
    description: "NetWeaver provides the application server foundation that enables SAP enterprise business applications to operate"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1190"
    tactic:
      - "Initial Access"
  defense_context:
    effectiveness: "critical"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "SAP Security Notes - SAP NetWeaver Advisories"
    - "MITRE ATT&CK T1190 - Exploit Public-Facing Application"
    - "CISA Alert AA22-216A - SAP NetWeaver Exploitation"
    - "CVE-2020-6287 RECON Vulnerability Analysis"
  search_keywords:
    - "SAP NetWeaver"
    - "NetWeaver vulnerability"
    - "SAP NetWeaver exploit"
    - "SAP RECON vulnerability"
    - "SAP ICM vulnerability"
    - "SAP Message Server"
    - "SAP security"
    - "CVE-2020-6287"
    - "SAP NetWeaver RCE"
  embedding_text: >-
    SAP NetWeaver is the technology platform and application server foundation for SAP enterprise
    applications including ERP, S/4HANA, and Business Suite. It provides ABAP and Java application
    stacks, the Internet Communication Manager (ICM) for HTTP processing, and the Message Server
    for internal routing. NetWeaver is a high-value target with critical vulnerabilities including
    RECON (CVE-2020-6287) enabling unauthenticated admin access and ICM memory corruption
    (CVE-2022-22536). CISA has issued multiple alerts for SAP NetWeaver exploitation. Attackers
    target the complex attack surface spanning ICM, Message Server, Java deserialization, and RFC
    Gateway for access to sensitive business data. Security teams should apply SAP Security Notes
    promptly, restrict access to administrative interfaces, configure Message Server ACLs, monitor
    SAP Gateway for unauthorized RFC calls, and implement network segmentation for SAP landscapes.
