# GR Atom: Oracle VSS Writer
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-ORAVSSWRI-001"
  name: "Oracle VSS Writer"
  normalized_name: "oracle_vss_writer"
  aliases:
    - "Oracle Volume Shadow Copy Writer"
    - "OracleVSSWriter"
    - "Oracle VSS Service"
    - "OracleVSSWriterORCL"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 1
  atom_tags:
    - WINDOWS
    - OS
    - PRIV
    - PERSIST

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "D1.3"

# ==== Section 5: Definition ====
definition:
  what: >-
    Oracle VSS Writer is a Windows service that integrates Oracle Database with the Windows
    Volume Shadow Copy Service (VSS) framework. It enables consistent backup operations of
    Oracle databases by coordinating with VSS to create application-consistent snapshots. The
    service runs as OracleVSSWriterORCL (or similar instance-named variants) and communicates
    with the VSS infrastructure to quiesce Oracle database I/O during shadow copy creation,
    ensuring backup integrity without requiring database shutdown.
  why: >-
    Oracle VSS Writer is a security-relevant Windows service because it runs with elevated
    privileges (typically Local System) and interacts with both the Oracle Database and Windows
    VSS infrastructure. Ransomware operators specifically target VSS writers and the VSS
    infrastructure to delete shadow copies before encrypting files, preventing backup-based
    recovery. Attackers may stop or disable the Oracle VSS Writer service to prevent consistent
    database backups. The service's elevated privileges make it a potential target for privilege
    escalation. Misconfigured service permissions can allow unauthorized users to manipulate
    backup operations or access database-level functionality through the VSS interface.
  how: >-
    Oracle VSS Writer runs as a Windows service registered with the VSS framework. During backup
    operations, the VSS coordinator signals the Oracle VSS Writer to prepare the database for
    snapshot creation. The writer places the Oracle database in backup mode, flushes buffers,
    and signals readiness. After the shadow copy is created, the writer resumes normal database
    operations. Ransomware attacks target this service by stopping it (net stop OracleVSSWriterORCL)
    or by deleting shadow copies through vssadmin commands. Privilege escalation targets the
    service's Local System context. Service manipulation attacks modify the service configuration
    to execute arbitrary code at system privilege level.
  core_concepts:
    - key: "Database Backup Integration"
      value: "Windows service integrating Oracle Database with VSS for application-consistent shadow copy backups without database shutdown"
    - key: "Ransomware Target"
      value: "Targeted by ransomware operators to disable database backup capabilities before encryption, preventing backup-based recovery"
    - key: "Privileged Windows Service"
      value: "Runs with Local System privileges creating privilege escalation opportunities through service manipulation or configuration tampering"

# ==== Section 6: Relations ====
relations:
  - type: "part_of"
    target: "INFRA-APP-ORACLE-001"
    description: "Oracle VSS Writer is a component of the Oracle Database installation that provides VSS integration for backup operations"
  - type: "requires"
    target: "INFRA-APP-ORACLE-001"
    description: "Oracle VSS Writer requires a running Oracle Database instance to perform its backup coordination functions"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1490"
    tactic:
      - "Impact"
  defense_context:
    effectiveness: "medium"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Oracle Database Backup and Recovery Documentation"
    - "MITRE ATT&CK T1490 - Inhibit System Recovery"
    - "Ransomware Analysis - VSS Writer Targeting Patterns"
  search_keywords:
    - "Oracle VSS Writer"
    - "OracleVSSWriter"
    - "Oracle backup security"
    - "VSS Writer ransomware"
    - "Oracle shadow copy"
    - "VSS Writer privilege escalation"
    - "Oracle VSS service"
  embedding_text: >-
    Oracle VSS Writer is a Windows service integrating Oracle Database with the Volume Shadow
    Copy Service (VSS) framework for application-consistent backup snapshots. It runs with Local
    System privileges and coordinates database I/O quiescing during shadow copy creation.
    Ransomware operators specifically target VSS writers to delete shadow copies and prevent
    backup-based recovery before encrypting files. The service's elevated privileges create
    privilege escalation opportunities through service manipulation. Attackers stop the service
    (net stop OracleVSSWriterORCL) or delete shadow copies via vssadmin to disable recovery
    capabilities. Security teams should protect VSS Writer services from unauthorized
    modification, monitor for service stop events, restrict vssadmin access, implement
    immutable backup strategies, and ensure Oracle VSS Writer service permissions follow
    least-privilege principles.
