# GR Atom: Exchange Server
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-EXCHSERV-001"
  name: "Exchange Server"
  normalized_name: "exchange_server"
  aliases:
    - "Microsoft Exchange Server"
    - "Exchange On-Premises"
    - "Exchange Mailbox Server"
    - "MS Exchange"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 1
  atom_tags:
    - WINDOWS
    - SMTP
    - HTTP
    - WEB
    - EXEC

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L7"
  zone: "Z1"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    Microsoft Exchange Server is an on-premises email server and calendaring platform that
    provides enterprise messaging, calendaring, contacts, and task management. It runs on
    Windows Server and includes components for mail transport (Hub Transport), client access
    (CAS), mailbox storage, and unified messaging. Exchange Server exposes services through
    Outlook Web App (OWA), Exchange Web Services (EWS), MAPI/HTTP, Exchange ActiveSync,
    Autodiscover, and SMTP for mail flow.
  why: >-
    Exchange Server is one of the most targeted enterprise applications in cybersecurity.
    Critical vulnerabilities including ProxyLogon (CVE-2021-26855), ProxyShell (CVE-2021-34473),
    ProxyNotShell (CVE-2022-41040), and OWASSRF have been massively exploited by nation-state
    actors and ransomware groups for initial access. Exchange's internet-facing services (OWA,
    Autodiscover, EWS) provide direct attack surfaces. Post-compromise, Exchange provides
    access to all organizational email, enables lateral movement through Active Directory
    integration, and can be used as a platform for persistent access through web shells.
  how: >-
    Exchange Server processes email through transport pipelines, stores mailboxes in Exchange
    databases (EDB files), and serves clients through IIS-hosted web services. The Client
    Access Services proxy requests to backend mailbox servers. Exchange integrates deeply with
    Active Directory for authentication, recipient management, and topology information.
    Exploitation typically targets the CAS/IIS frontend through SSRF vulnerabilities
    (ProxyLogon), authentication bypass, or deserialization flaws. Post-exploitation involves
    web shell deployment (often in OWA directories), mailbox exfiltration through EWS, and
    credential harvesting from Exchange's privileged AD access.
  core_concepts:
    - key: "Enterprise Email Platform"
      value: "On-premises messaging server providing email, calendaring, and collaboration through multiple client access protocols and deep Active Directory integration"
    - key: "Critical Attack Surface"
      value: "Internet-facing services (OWA, EWS, Autodiscover) have been subject to ProxyLogon, ProxyShell, and ProxyNotShell exploitation chains by nation-state actors"
    - key: "Post-Exploitation Platform"
      value: "Compromised Exchange provides access to all organizational email, web shell persistence in IIS, and privileged Active Directory access for lateral movement"

# ==== Section 6: Relations ====
relations:
  - type: "requires"
    target: "INFRA-IDENTITY-AZUACTDIR-001"
    description: "Exchange Server deeply integrates with Active Directory for authentication, recipient management, and topology"
  - type: "part_of"
    target: "INFRA-APP-ENTESERV-001"
    description: "Exchange Server is a core enterprise service in organizational infrastructure"
  - type: "enables"
    target: "INFRA-APP-EXCHCERT-001"
    description: "Exchange Server uses certificates for TLS encryption across all its communication services"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1190"
    tactic:
      - "Initial Access"
      - "Persistence"
      - "Collection"
  defense_context:
    effectiveness: "critical"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Microsoft Exchange Server Security Documentation"
    - "CISA Emergency Directive 21-02 - Microsoft Exchange Vulnerabilities"
    - "MITRE ATT&CK T1190 - Exploit Public-Facing Application"
    - "Volexity ProxyLogon Analysis - CVE-2021-26855"
  search_keywords:
    - "Exchange Server"
    - "Microsoft Exchange"
    - "ProxyLogon"
    - "ProxyShell"
    - "Exchange vulnerability"
    - "Exchange web shell"
    - "CVE-2021-26855"
    - "Exchange Server exploit"
    - "OWA vulnerability"
  embedding_text: >-
    Microsoft Exchange Server is an on-premises email and calendaring platform running on
    Windows Server, providing enterprise messaging through OWA, EWS, MAPI/HTTP, ActiveSync,
    and SMTP. Exchange is one of the most targeted enterprise applications with critical
    vulnerability chains including ProxyLogon (CVE-2021-26855), ProxyShell (CVE-2021-34473),
    and ProxyNotShell (CVE-2022-41040) massively exploited by nation-state actors and
    ransomware groups. Internet-facing services provide direct attack surfaces for SSRF,
    authentication bypass, and deserialization exploits. Post-compromise, Exchange enables
    web shell persistence in IIS directories, complete organizational email exfiltration
    through EWS, and lateral movement through privileged Active Directory integration.
    Security teams should prioritize Exchange patching, restrict internet-facing services,
    monitor for web shells, and implement Exchange-specific detection rules.
