# GR Atom: LibreOffice
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-LIBREOFFIC-001"
  name: "LibreOffice"
  normalized_name: "libreoffice"
  aliases:
    - "The Document Foundation LibreOffice"
    - "LibreOffice Suite"
    - "LibreOffice Writer"
    - "LibreOffice Calc"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - LINUX
    - EXEC
    - INITIAL
    - INJ

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L7"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    LibreOffice is a free, open-source office productivity suite developed by The Document
    Foundation. It includes Writer (word processing), Calc (spreadsheets), Impress
    (presentations), Draw (vector graphics), Base (databases), and Math (formula editor).
    LibreOffice supports ODF, Microsoft Office formats, and includes a macro system based
    on StarBasic and Python. It is the default office suite on most Linux distributions and
    is available for Windows and macOS.
  why: >-
    LibreOffice processes complex document formats that can contain embedded macros, OLE
    objects, and external links, creating exploitation vectors similar to Microsoft Office.
    Vulnerabilities have included macro execution bypasses, path traversal in document links,
    and buffer overflows in format parsers. LibreOffice macros (StarBasic) can execute system
    commands and access the filesystem. Crafted documents can exploit LibreOffice for initial
    access through phishing campaigns targeting Linux users where Microsoft Office is not
    available. CVE-2023-6185 and CVE-2023-6186 demonstrated macro security bypasses.
  how: >-
    LibreOffice processes documents through format-specific parsers handling ODF, OOXML, RTF,
    and legacy formats. The macro engine executes StarBasic or Python scripts embedded in
    documents. Document security levels control macro execution (disabled, medium with prompt,
    low). OLE objects and external links can reference system resources. Exploitation targets
    macro security bypasses to execute code without user consent, format parser vulnerabilities
    for memory corruption, and document link manipulation for information disclosure. Phishing
    campaigns deliver crafted ODF or OOXML documents with malicious macros to Linux targets.
  core_concepts:
    - key: "Open-Source Office Suite"
      value: "Default Linux office productivity suite processing complex document formats with embedded macro, OLE, and external link capabilities"
    - key: "Macro Execution Risks"
      value: "StarBasic and Python macro engines can execute system commands and access filesystems with macro security bypass vulnerabilities enabling code execution"
    - key: "Linux Phishing Vector"
      value: "Primary document processing target for phishing campaigns against Linux users where Microsoft Office is not typically installed"

# ==== Section 6: Relations ====
relations:
  - type: "alternative_to"
    target: "INFRA-APP-OPENOFFICE-001"
    description: "LibreOffice is a fork of OpenOffice and serves as its alternative with more active development"
  - type: "is_a"
    target: "INFRA-APP-ENTEAPPS-001"
    description: "LibreOffice is an enterprise office application deployed across Linux-based organizational desktops"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1204.002"
    tactic:
      - "Execution"
      - "Initial Access"
  defense_context:
    effectiveness: "high"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "The Document Foundation - LibreOffice Security Advisories"
    - "MITRE ATT&CK T1204.002 - Malicious File"
    - "CVE-2023-6185 CVE-2023-6186 - LibreOffice Macro Security Bypass"
  search_keywords:
    - "LibreOffice"
    - "LibreOffice vulnerability"
    - "LibreOffice macro"
    - "LibreOffice exploit"
    - "LibreOffice security"
    - "StarBasic macro"
    - "ODF security"
    - "LibreOffice phishing"
  embedding_text: >-
    LibreOffice is a free open-source office productivity suite by The Document Foundation,
    the default on most Linux distributions. It includes Writer, Calc, Impress, and supports
    ODF and Microsoft Office formats with StarBasic and Python macro engines. Security concerns
    include macro execution bypasses (CVE-2023-6185, CVE-2023-6186) enabling code execution
    without user consent, format parser vulnerabilities, and document link manipulation.
    LibreOffice is the primary document-based phishing vector against Linux users. Crafted
    documents with malicious macros target the StarBasic engine for system command execution.
    Security teams should enforce macro security policies, disable macros by default, keep
    LibreOffice updated, and train users on malicious document awareness for Linux environments.
