# GR Atom: AWS KMS
# Schema: atom_schema.yaml v5.1
# Status: enriched

identity:
  id: "INFRA-DEVOPS-AWSKMS-001"
  name: "AWS KMS"
  normalized_name: "aws_kms"
  aliases:
    - "Amazon Key Management Service"
    - "KMS"
    - "AWS Key Management"

classification:
  is_infrastructure: true
  type: "component_control"
  abstraction_level: 2
  atom_tags:
    - AWS
    - CRYPTO
    - ENCRYPT
    - CLOUD
    - COMPLIANCE

gr_coordinates:
  layer: "L5"
  zone: "Z3"
  function: "P2.2"

definition:
  what: "AWS Key Management Service (KMS) is a managed cryptographic key management service that enables creation, storage, rotation, and auditing of encryption keys used to protect data across AWS services and custom applications. It provides centralized control over customer master keys (CMKs) backed by FIPS 140-2 validated hardware security modules (HSMs), supporting both symmetric and asymmetric key operations including encryption, decryption, digital signing, and key generation."
  why: "KMS is fundamental to data protection in AWS environments because it governs the cryptographic keys that safeguard data at rest and in transit. Compromise of KMS keys or policies can lead to complete exposure of encrypted data across S3, EBS, RDS, and other services. Attackers target KMS key policies, grants, and IAM permissions to gain unauthorized decryption capabilities. Proper KMS configuration is required for regulatory compliance frameworks including PCI DSS, HIPAA, and SOC 2."
  how: "KMS integrates natively with over 100 AWS services through envelope encryption, where data keys are encrypted under CMKs stored in HSMs. Key policies and IAM policies control access to cryptographic operations. Automatic key rotation occurs annually for AWS-managed keys. CloudTrail logs all KMS API calls for audit purposes. Custom key stores can be backed by AWS CloudHSM clusters for additional control. KMS supports multi-region keys for disaster recovery and cross-region encryption scenarios."
  core_concepts:
    - key: "Customer Master Key (CMK)"
      value: "The primary cryptographic resource in KMS, representing a logical key that never leaves KMS unencrypted and controls access to data encryption keys"
    - key: "Envelope Encryption"
      value: "A strategy where data is encrypted with a data key, and the data key itself is encrypted under a CMK, enabling efficient encryption of large datasets"
    - key: "Key Policy"
      value: "Resource-based policy attached to each CMK that defines which principals can use and manage the key, serving as the primary access control mechanism"
    - key: "Key Rotation"
      value: "Automatic or manual process of generating new cryptographic material for a CMK while retaining old material for decryption of previously encrypted data"

relations:
  - type: part_of
    target: "INFRA-COMPUTE-AWS-001"
    description: "KMS is a core security service within the AWS cloud platform"
  - type: enables
    target: "INFRA-DEVOPS-AWS3OBLO-001"
    description: "KMS provides the encryption keys used by S3 Object Lock for server-side encryption of locked objects"
  - type: instance_of
    target: "INFRA-DEVOPS-KEYVAUL-001"
    description: "AWS KMS is a specific implementation of the general key vault infrastructure pattern"

security_profile:
  mitre_mapping:
    technique_id: "T1588.004"
    tactic: ["Resource Development"]

metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "AWS KMS Documentation - https://docs.aws.amazon.com/kms/"
    - "AWS KMS Cryptographic Details Whitepaper - https://docs.aws.amazon.com/kms/latest/cryptographic-details/"
    - "MITRE ATT&CK T1588.004 - Obtain Capabilities: Digital Certificates"
  search_keywords:
    - "AWS KMS"
    - "Amazon Key Management Service"
    - "AWS encryption keys"
    - "KMS CMK"
    - "AWS key management"
    - "envelope encryption AWS"
    - "KMS key policy"
    - "AWS HSM keys"
  embedding_text: "AWS Key Management Service (KMS) is Amazon's managed cryptographic key management service for creating, storing, rotating, and auditing encryption keys across AWS services and applications. It uses FIPS 140-2 validated HSMs to protect customer master keys (CMKs) and supports symmetric and asymmetric operations including encryption, decryption, and digital signing. KMS employs envelope encryption where data keys are encrypted under CMKs. It integrates natively with S3, EBS, RDS, and over 100 AWS services. Security significance includes centralized key governance, automated rotation, CloudTrail audit logging, and IAM-based access control. Compromise of KMS keys or policies can expose all encrypted data across an AWS environment."
