# GR Atom: DISM Core
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-COMPUTE-DISMCORE-001"
  name: "DISM Core"
  normalized_name: "dism_core"
  aliases:
    - "Deployment Image Servicing and Management Core"
    - "DISM.exe Core"
    - "DismCore.dll"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WINDOWS
    - OS
    - PATCH

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "P3.1"

# ==== Section 5: Definition ====
definition:
  what: >-
    DISM Core is the foundational component of the Windows Deployment Image Servicing and
    Management (DISM) framework, implemented as DismCore.dll. It provides the core API and
    engine for servicing Windows images, including adding or removing Windows features, drivers,
    packages, and updates to both online (running) and offline (mounted WIM/VHD) Windows images.
    DISM Core orchestrates the various DISM providers that handle specific servicing operations.
  why: >-
    DISM Core is a critical Windows system component that can be abused for persistence and
    defense evasion. Attackers can use DISM to install malicious drivers, enable vulnerable
    Windows features, or modify offline Windows images used for deployment. DISM operations
    require elevated privileges, making it a target for privilege escalation attacks. Monitoring
    DISM activity is important for detecting unauthorized system modifications.
  how: >-
    DISM Core operates through a provider architecture where specialized DLLs handle different
    servicing operations (packages, features, drivers, app packages). It exposes functionality
    through the DISM command-line tool (dism.exe), PowerShell cmdlets, and the DISM API
    (DismApi.dll). Operations include mounting images, adding/removing features, injecting
    drivers, applying updates, and cleaning up component stores. DISM Core loads provider
    DLLs dynamically and coordinates their operations against the target image.
  core_concepts:
    - key: "Image Servicing Engine"
      value: "Core engine managing Windows image modifications including feature, driver, package, and update operations on online and offline images"
    - key: "Provider Architecture"
      value: "Extensible plugin system where specialized DLLs handle different image servicing operations through a common interface"
    - key: "Offline Image Manipulation"
      value: "Ability to modify Windows images before deployment, creating supply chain risk if deployment images are compromised"

# ==== Section 6: Relations ====
relations:
  - type: "enables"
    target: "INFRA-COMPUTE-DISMHOST-001"
    description: "DISM Core provides the servicing engine that DISM Host loads and orchestrates"
  - type: "enables"
    target: "INFRA-COMPUTE-DRIVSTOR-001"
    description: "DISM Core manages driver injection into the Windows Driver Store"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "derived"
  sources:
    - "Microsoft DISM Technical Reference"
    - "Microsoft Windows Deployment Documentation"
    - "MITRE ATT&CK T1218 - System Binary Proxy Execution"
  search_keywords:
    - "DISM core"
    - "dismcore.dll"
    - "deployment image servicing"
    - "windows image servicing"
    - "DISM API"
    - "windows deployment"
    - "DISM providers"
  embedding_text: >-
    DISM Core (DismCore.dll) is the foundational component of the Windows Deployment Image
    Servicing and Management framework, providing the core API and engine for servicing Windows
    images. It manages adding or removing features, drivers, packages, and updates to both
    running and offline Windows images through a provider architecture. DISM Core is a security
    concern because it can be abused for installing malicious drivers, enabling vulnerable
    features, or modifying deployment images. Operations require elevated privileges. Monitoring
    DISM activity is important for detecting unauthorized system modifications and supply chain
    attacks targeting deployment images.
