# GR Atom: Oracle Service
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-ORACLE-001"
  name: "Oracle Service"
  normalized_name: "oracle_service"
  aliases:
    - "Oracle Database"
    - "Oracle DB"
    - "Oracle RDBMS"
    - "Oracle TNS Listener"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - DATABASE
    - INJ
    - PRIV
    - CONFIG
    - NETWORK

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L5"
  zone: "Z2"
  function: "D1.3"

# ==== Section 5: Definition ====
definition:
  what: >-
    Oracle Service refers to the Oracle Database management system and its associated services
    including the TNS Listener (port 1521), Oracle Net Services, and Oracle Enterprise Manager.
    Oracle Database is a multi-model relational database management system widely deployed in
    enterprise environments for critical business applications, financial systems, and data
    warehousing. The TNS Listener handles client connections, and Oracle services include
    background processes for database management, recovery, and replication.
  why: >-
    Oracle Database is a high-value target containing critical enterprise data including financial
    records, personal information, and business intelligence. SQL injection vulnerabilities in
    applications using Oracle backends enable data exfiltration and privilege escalation. The TNS
    Listener has been exploited for remote code execution and denial of service. Oracle's PL/SQL
    execution environment allows stored procedure exploitation for privilege escalation. Default
    accounts (SYS, SYSTEM, SCOTT, DBSNMP) with known default passwords are commonly found in
    penetration tests. Oracle Critical Patch Updates (CPUs) address numerous vulnerabilities
    quarterly, and unpatched systems accumulate significant risk.
  how: >-
    Oracle Database listens for client connections through the TNS Listener on port 1521. The TNS
    protocol handles authentication, session management, and query routing. SQL injection targets
    PL/SQL procedures and application queries to extract data or escalate privileges. The Oracle
    Java VM within the database enables Java-based exploitation. TNS poisoning attacks redirect
    client connections through attacker-controlled proxies. Privilege escalation exploits target
    PL/SQL package vulnerabilities (DBMS_JAVA, DBMS_XMLGEN) to gain DBA privileges from low-
    privileged accounts. Oracle Enterprise Manager vulnerabilities enable administrative access
    to database infrastructure.
  core_concepts:
    - key: "Enterprise Database System"
      value: "Multi-model RDBMS widely deployed for critical enterprise applications containing financial, personal, and business intelligence data"
    - key: "SQL Injection and Privilege Escalation"
      value: "SQL injection in Oracle-backed applications and PL/SQL package vulnerabilities enable data exfiltration and escalation to DBA privileges"
    - key: "TNS Listener Attack Surface"
      value: "TNS Listener on port 1521 targeted for connection poisoning, remote code execution, and denial of service attacks"

# ==== Section 6: Relations ====
relations:
  - type: "is_a"
    target: "INFRA-APP-ENTESERV-001"
    description: "Oracle Database is an enterprise server service providing relational database capabilities for business applications"
  - type: "enables"
    target: "INFRA-APP-ENTEAPPS-001"
    description: "Oracle Database provides the data persistence layer enabling enterprise business applications to store and retrieve critical data"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1505.001"
    tactic:
      - "Persistence"
      - "Privilege Escalation"
  defense_context:
    effectiveness: "critical"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Oracle Critical Patch Updates (CPU) Advisories"
    - "MITRE ATT&CK T1505.001 - SQL Stored Procedures"
    - "Oracle Database Security Best Practices Guide"
    - "TNS Listener Security Analysis"
  search_keywords:
    - "Oracle Database"
    - "Oracle vulnerability"
    - "Oracle TNS Listener"
    - "Oracle SQL injection"
    - "Oracle privilege escalation"
    - "Oracle default passwords"
    - "Oracle security"
    - "Oracle Critical Patch Update"
    - "Oracle PL/SQL exploit"
  embedding_text: >-
    Oracle Service encompasses the Oracle Database RDBMS and associated services including the
    TNS Listener (port 1521) and Oracle Enterprise Manager. Oracle Database is widely deployed
    in enterprise environments for critical business applications containing financial and
    personal data. Security concerns include SQL injection in Oracle-backed applications, PL/SQL
    package vulnerabilities (DBMS_JAVA, DBMS_XMLGEN) enabling privilege escalation to DBA, TNS
    Listener exploitation for connection poisoning and RCE, and default account credentials.
    Oracle Critical Patch Updates address numerous vulnerabilities quarterly. The Oracle Java VM
    within the database enables Java-based exploitation. Security teams should apply CPUs
    promptly, change default passwords, restrict TNS Listener access, audit PL/SQL stored
    procedures, implement least-privilege database accounts, and monitor for SQL injection
    patterns and anomalous database queries.
