# GR Atom: Service Host
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-SERVHOST-001"
  name: "Service Host"
  normalized_name: "service_host"
  aliases:
    - "svchost.exe"
    - "Service Host Process"
    - "Windows Service Host"
    - "Generic Host Process for Win32 Services"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WINDOWS
    - OS
    - EVADE
    - EXEC
    - PERSIST

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    Service Host (svchost.exe) is a critical Windows system process that serves as a generic
    host for services that run from dynamic-link libraries (DLLs). Multiple instances of
    svchost.exe run simultaneously, each hosting one or more Windows services grouped by
    shared service accounts and resource requirements. It is the most prevalent process on
    Windows systems, hosting essential services including Windows Update, DHCP Client, DNS
    Client, Windows Firewall, Task Scheduler, and dozens of other core system services.
  why: >-
    Svchost.exe is one of the most commonly abused processes for defense evasion because its
    ubiquity and multiple instances make malicious activity harder to detect. Attackers disguise
    malware as svchost.exe by placing executables with the same name in non-standard directories.
    DLL injection and DLL sideloading attacks target svchost.exe to execute malicious code within
    a trusted process context. Service creation attacks register malicious DLLs as Windows services
    that load into legitimate svchost.exe instances. Process hollowing techniques use svchost.exe
    as a target due to its trusted status and multiple running instances.
  how: >-
    Svchost.exe loads service DLLs specified in the registry under
    HKLM\SYSTEM\CurrentControlSet\Services\<ServiceName>\Parameters\ServiceDll. The Service
    Control Manager (SCM) starts svchost.exe with a -k parameter specifying the service group,
    and the process loads all service DLLs assigned to that group. Each svchost.exe instance
    runs under a specific service account (LocalSystem, LocalService, NetworkService, or
    custom accounts). Modern Windows versions (10+) tend to isolate services into individual
    svchost.exe instances for improved reliability and security.
  core_concepts:
    - key: "Service DLL Hosting"
      value: "Svchost.exe loads service DLLs from registry-specified paths, and attackers register malicious DLLs as services to execute code within the trusted process"
    - key: "Defense Evasion Through Ubiquity"
      value: "Multiple svchost.exe instances running simultaneously on every Windows system make it an ideal target for process masquerading and DLL injection"
    - key: "Process Integrity Verification"
      value: "Legitimate svchost.exe only runs from %SystemRoot%\\System32, and the binary is digitally signed by Microsoft, providing verification markers"

# ==== Section 6: Relations ====
relations:
  - type: "enables"
    target: "INFRA-APP-PRINSERV-001"
    description: "Service Host hosts the Print Spooler service DLL"
  - type: "enables"
    target: "INFRA-APP-TASKSCHE-001"
    description: "Service Host hosts the Task Scheduler service"
  - type: "enables"
    target: "INFRA-APP-SEARINDE-001"
    description: "Service Host provides the hosting infrastructure for Windows Search service"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1055.012"
    tactic:
      - "Defense Evasion"
      - "Privilege Escalation"
      - "Execution"
  defense_context:
    effectiveness: "low"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Microsoft Windows Service Host Documentation"
    - "MITRE ATT&CK T1055.012 - Process Hollowing"
    - "Microsoft Defender Security Research - Svchost Analysis"
  search_keywords:
    - "svchost.exe"
    - "Service Host"
    - "Windows service host"
    - "svchost malware"
    - "DLL injection svchost"
    - "process hollowing svchost"
    - "service DLL loading"
    - "svchost defense evasion"
  embedding_text: >-
    Service Host (svchost.exe) is the Windows generic host process for DLL-based services,
    running multiple instances simultaneously to host essential system services. It loads
    service DLLs from registry-specified paths under specific service accounts. Svchost.exe
    is heavily targeted for defense evasion due to its ubiquity, with attackers using process
    masquerading, DLL injection, DLL sideloading, service creation with malicious DLLs, and
    process hollowing techniques. Legitimate svchost.exe runs only from System32 and is
    Microsoft-signed. Security teams should monitor for svchost.exe instances running from
    non-standard paths, unexpected service DLL registrations, anomalous parent processes,
    and suspicious DLL loading patterns to detect abuse of this critical system process.
