# GR Atom: Restart Manager
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-RESTMANA-001"
  name: "Restart Manager"
  normalized_name: "restart_manager"
  aliases:
    - "Windows Restart Manager"
    - "RmStartSession"
    - "Rstrtmgr.dll"
    - "Application Restart Manager"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WINDOWS
    - OS
    - EVADE
    - PERSIST
    - CONFIG

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    Windows Restart Manager is an operating system API and service (rstrtmgr.dll) that reduces
    the number of system restarts required during software installations and updates. It
    identifies which processes are using files that need to be replaced, shuts down those
    processes gracefully, allows the installer to replace the files, and then restarts the
    affected processes. This functionality is integrated into Windows Installer (MSI) and
    available through a public API for custom installers.
  why: >-
    Restart Manager can be abused by malware to unlock files held by security processes,
    enabling modification or deletion of protected files. Ransomware families including
    Conti, REvil, and LockBit use the Restart Manager API to close applications that have
    open handles on target files, allowing encryption of otherwise locked files such as
    databases and documents. Attackers can also use it to gracefully terminate security
    software before deploying payloads, or to restart modified services to load malicious
    code without requiring a full system reboot.
  how: >-
    Restart Manager operates through the RmStartSession, RmRegisterResources, RmGetList,
    RmShutdown, and RmRestart API functions exported from rstrtmgr.dll. Callers register
    file paths or process IDs, then query which processes hold handles. RmShutdown sends
    WM_CLOSE, application-specific shutdown commands, or forcefully terminates processes
    depending on configuration. After file operations complete, RmRestart relaunches the
    previously closed applications. The API requires SeDebugPrivilege for full functionality
    across all processes.
  core_concepts:
    - key: "File Lock Bypass"
      value: "Restart Manager can terminate processes holding file locks, enabling ransomware to encrypt database files and documents that would otherwise be inaccessible"
    - key: "Ransomware Integration"
      value: "Major ransomware families (Conti, REvil, LockBit) incorporate Restart Manager API calls to maximize file encryption coverage"
    - key: "Security Software Termination"
      value: "Attackers abuse Restart Manager to gracefully shut down security tools before deploying malicious payloads"

# ==== Section 6: Relations ====
relations:
  - type: "part_of"
    target: "INFRA-APP-SERVHOST-001"
    description: "Restart Manager operates as a system-level API within the Windows Service Host infrastructure"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1489"
    tactic:
      - "Impact"
      - "Defense Evasion"
  defense_context:
    effectiveness: "low"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Microsoft Restart Manager API Documentation"
    - "MITRE ATT&CK T1489 - Service Stop"
    - "Ransomware Analysis Reports - Conti, REvil, LockBit"
  search_keywords:
    - "Restart Manager"
    - "rstrtmgr.dll"
    - "RmStartSession"
    - "Windows Restart Manager"
    - "ransomware file lock bypass"
    - "process termination API"
    - "file handle release"
    - "Conti Restart Manager"
  embedding_text: >-
    Windows Restart Manager is an OS API (rstrtmgr.dll) that manages process shutdown and
    restart during software installations to reduce system reboots. It identifies processes
    holding file handles, terminates them gracefully, and restarts them after file operations.
    Ransomware families including Conti, REvil, and LockBit abuse the Restart Manager API
    to close applications with open file handles, enabling encryption of otherwise locked
    databases and documents. Attackers also use it to terminate security software before
    payload deployment. The API functions RmStartSession, RmShutdown, and RmRestart
    require SeDebugPrivilege for cross-process operations. Security teams should monitor
    for suspicious Restart Manager API calls, especially from non-installer processes,
    and implement application whitelisting to prevent unauthorized use.
