# GR Atom: Remote Connection Manager
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-REMCONMAN-001"
  name: "Remote Connection Manager"
  normalized_name: "remote_connection_manager"
  aliases:
    - "RCM"
    - "SessionEnv"
    - "Remote Desktop Configuration"
    - "TermService"
    - "RDP Connection Manager"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WINDOWS
    - RDP
    - LATERAL
    - AUTHN
    - CONFIG

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    Remote Connection Manager is a Windows service component responsible for managing Remote
    Desktop Protocol (RDP) connections and sessions. It works in conjunction with the Terminal
    Services service (TermService) and Remote Desktop Configuration service (SessionEnv) to
    handle connection establishment, session creation, authentication handoff, and session
    lifecycle management. The service manages listener configurations, session mapping, and
    connection brokering for Remote Desktop Services.
  why: >-
    Remote Connection Manager is a critical component in RDP-based attacks as it controls
    the session establishment process. Vulnerabilities in the RDP stack, such as BlueKeep
    (CVE-2019-0708), directly affect the connection management layer. Attackers target this
    service for session hijacking, where an administrative user can connect to disconnected
    sessions without credentials. The service configuration determines NLA enforcement and
    encryption levels, and misconfigurations weaken the entire RDP security posture.
  how: >-
    Remote Connection Manager operates as a Windows service that listens on TCP port 3389
    (default) for incoming RDP connections. It coordinates with the credential security
    support provider (CredSSP) for NLA authentication, establishes session environments
    through SessionEnv, and manages session state transitions (active, disconnected,
    idle). The service interfaces with the Windows security subsystem for authentication
    and maintains session-to-user mappings. Configuration is managed through Group Policy,
    registry settings, and the Remote Desktop Session Host Configuration tool.
  core_concepts:
    - key: "RDP Session Lifecycle Management"
      value: "Controls connection establishment, authentication handoff, session creation, disconnection, and reconnection for all RDP sessions"
    - key: "BlueKeep Attack Surface"
      value: "Pre-authentication vulnerabilities like CVE-2019-0708 in the RDP connection handling layer enable remote code execution without credentials"
    - key: "Session Hijacking Risk"
      value: "Administrative users can connect to disconnected sessions via tscon.exe without re-authentication, enabling privilege escalation"

# ==== Section 6: Relations ====
relations:
  - type: "enables"
    target: "INFRA-APP-TERMSERV-001"
    description: "Remote Connection Manager provides the connection handling infrastructure that enables Terminal Services sessions"
  - type: "enables"
    target: "INFRA-APP-REMOAPP-001"
    description: "RemoteApp depends on Remote Connection Manager for RDP connection establishment"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1563.002"
    tactic:
      - "Lateral Movement"
      - "Privilege Escalation"
  defense_context:
    effectiveness: "medium"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Microsoft Remote Desktop Services Architecture Documentation"
    - "MITRE ATT&CK T1563.002 - RDP Hijacking"
    - "CVE-2019-0708 BlueKeep Advisory"
  search_keywords:
    - "Remote Connection Manager"
    - "RDP connection manager"
    - "TermService"
    - "SessionEnv"
    - "BlueKeep"
    - "CVE-2019-0708"
    - "RDP session hijacking"
    - "Remote Desktop session management"
  embedding_text: >-
    Remote Connection Manager is a Windows service that manages RDP connection establishment,
    authentication handoff, and session lifecycle for Remote Desktop Services. It listens on
    TCP port 3389, coordinates with CredSSP for Network Level Authentication, and manages
    session state transitions. The service is directly affected by pre-authentication
    vulnerabilities like BlueKeep (CVE-2019-0708) enabling remote code execution. Session
    hijacking attacks use tscon.exe to connect to disconnected sessions without credentials.
    Service configuration controls NLA enforcement and encryption levels, making
    misconfiguration a significant risk. Security teams should enforce NLA, patch RDP
    stack vulnerabilities promptly, restrict RDP access through network segmentation and
    firewalls, and monitor for session hijacking indicators.
