# GR Atom: Search Indexer
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-SEARINDE-001"
  name: "Search Indexer"
  normalized_name: "search_indexer"
  aliases:
    - "Windows Search Indexer"
    - "SearchIndexer.exe"
    - "Windows Search Service"
    - "WSearch"
    - "SearchProtocolHost.exe"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WINDOWS
    - OS
    - PRIV
    - INFO_LEAK
    - DISC

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    Windows Search Indexer (SearchIndexer.exe) is a Windows service that creates and maintains
    a full-text index of files, emails, and other content on local and mapped drives. The
    WSearch service continuously monitors file system changes and updates the search index
    stored in Windows.edb (an ESE database). It uses protocol handlers and filter DLLs (IFilters)
    to extract text content from various file formats. The index enables fast content search
    through Windows Explorer, Start menu search, and programmatic queries via the Windows
    Search API.
  why: >-
    Windows Search Indexer has been subject to multiple privilege escalation vulnerabilities
    due to its SYSTEM-level execution context and complex file parsing operations. IFilter
    DLLs loaded by the indexer can be exploited through malicious file content, as the
    service parses untrusted data with elevated privileges. The Windows.edb index database
    contains extracted text from indexed files and can be a rich source of sensitive information
    for attackers performing post-compromise reconnaissance. Adversaries can query the search
    index to rapidly discover sensitive documents, credentials in files, and network share
    contents.
  how: >-
    SearchIndexer.exe runs as the SYSTEM account and monitors configured index locations
    for file changes using USN journal and file system notifications. When content changes,
    SearchProtocolHost.exe loads appropriate IFilter DLLs to extract text from documents.
    Extracted content is stored in the Windows.edb ESE database, typically located at
    %ProgramData%\Microsoft\Search\Data\Applications\Windows. Applications query the index
    through the ISearchQueryHelper COM interface or SQL-like syntax via OLE DB. Group Policy
    controls indexing scope, encrypted file handling, and remote index queries.
  core_concepts:
    - key: "SYSTEM-Level File Parsing"
      value: "SearchIndexer.exe runs as SYSTEM and loads IFilter DLLs to parse untrusted file content, creating privilege escalation opportunities through parser vulnerabilities"
    - key: "Index Database Intelligence"
      value: "Windows.edb contains extracted text from all indexed files, providing attackers with a searchable database of sensitive content for rapid post-compromise reconnaissance"
    - key: "IFilter Attack Surface"
      value: "Third-party IFilter DLLs extend parsing capabilities but introduce additional attack surface through potentially vulnerable document parsers"

# ==== Section 6: Relations ====
relations:
  - type: "part_of"
    target: "INFRA-APP-SERVHOST-001"
    description: "Windows Search Indexer runs as a service within the Windows Service Host infrastructure"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1083"
    tactic:
      - "Discovery"
      - "Privilege Escalation"
  defense_context:
    effectiveness: "medium"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Microsoft Windows Search Service Documentation"
    - "MITRE ATT&CK T1083 - File and Directory Discovery"
    - "Windows Search Indexer Privilege Escalation CVE Advisories"
  search_keywords:
    - "Windows Search Indexer"
    - "SearchIndexer.exe"
    - "WSearch service"
    - "Windows.edb"
    - "IFilter vulnerability"
    - "search indexer privilege escalation"
    - "SearchProtocolHost"
    - "search index forensics"
  embedding_text: >-
    Windows Search Indexer (SearchIndexer.exe) is a SYSTEM-level service that maintains a
    full-text index of files and content in the Windows.edb ESE database. It uses IFilter
    DLLs to parse various document formats and monitors file system changes for index updates.
    Security concerns include privilege escalation through parser vulnerabilities in IFilter
    DLLs processing untrusted content, information disclosure through the Windows.edb database
    containing extracted text from indexed files, and post-compromise reconnaissance by querying
    the search index for sensitive documents and credentials. Third-party IFilters extend
    the attack surface. Security teams should restrict indexing scope, monitor for anomalous
    search queries, protect Windows.edb from unauthorized access, and patch search indexer
    privilege escalation vulnerabilities promptly.
