# GR Atom: Task Scheduler
# Schema: atom_schema.yaml v5.1
# Status: enriched

# ==== Section 1: Identity ====
identity:
  id: "INFRA-APP-TASKSCHE-001"
  name: "Task Scheduler"
  normalized_name: "task_scheduler"
  aliases:
    - "Windows Task Scheduler"
    - "schtasks.exe"
    - "taskschd.msc"
    - "Schedule Service"
    - "Task Scheduler Service"

# ==== Section 2: Classification ====
classification:
  is_infrastructure: true
  type: "component"
  abstraction_level: 2
  atom_tags:
    - WINDOWS
    - OS
    - PERSIST
    - PRIV
    - EXEC

# ==== Section 3: GR Coordinates (INFRA only) ====
gr_coordinates:
  layer: "L4"
  zone: "Z2"
  function: "A1.5"

# ==== Section 5: Definition ====
definition:
  what: >-
    Windows Task Scheduler is a system service that enables scheduling of automated tasks
    (programs, scripts, and commands) to run at specified times, intervals, or in response
    to system events. It manages scheduled tasks through the Task Scheduler service,
    accessible via schtasks.exe command line, taskschd.msc MMC snap-in, and COM/WMI APIs.
    Tasks can execute with configurable user contexts including SYSTEM, and support triggers
    based on time, logon events, system events, and idle states.
  why: >-
    Task Scheduler is one of the most commonly abused persistence mechanisms in Windows
    environments. Attackers create scheduled tasks to maintain access across reboots,
    execute payloads at specific times, and escalate privileges by running tasks as SYSTEM.
    The Task Scheduler service itself has had privilege escalation vulnerabilities (ALPC
    interface, CVE-2018-8440). Task XML definitions can be manipulated to achieve persistence
    without triggering common security monitoring. Scheduled tasks can be created remotely
    via RPC for lateral movement and execution on remote systems.
  how: >-
    The Task Scheduler service runs as SYSTEM and manages task definitions stored as XML
    files in %SystemRoot%\System32\Tasks. Tasks are created via schtasks.exe, COM interfaces
    (ITaskService), or the PowerShell ScheduledTasks module. Each task specifies triggers
    (time, event, logon), actions (execute program, send email), conditions (idle, network),
    and settings (run as user, elevated). Remote task creation uses RPC over SMB (port 445)
    with the ITaskSchedulerService interface. Tasks can execute with any configured user
    account credentials or SYSTEM.
  core_concepts:
    - key: "Persistence Mechanism"
      value: "Scheduled tasks survive reboots and execute with configurable user contexts, making them a primary persistence technique for attackers (MITRE T1053.005)"
    - key: "Privilege Escalation Vector"
      value: "Tasks configured to run as SYSTEM combined with writable task directories or DLL hijacking enable privilege escalation"
    - key: "Remote Execution Channel"
      value: "Remote task creation via RPC enables attackers to execute code on remote systems using compromised credentials for lateral movement"

# ==== Section 6: Relations ====
relations:
  - type: "part_of"
    target: "INFRA-APP-SERVHOST-001"
    description: "Task Scheduler runs as a service hosted within the Windows Service Host infrastructure"

# ==== Section 7: Security Profile ====
security_profile:
  mitre_mapping:
    technique_id: "T1053.005"
    tactic:
      - "Execution"
      - "Persistence"
      - "Privilege Escalation"
  defense_context:
    effectiveness: "low"

# ==== Section 8: Metadata ====
metadata:
  created: "2026-02-06"
  updated: "2026-02-10"
  version: "1.0"
  confidence: "high"
  trust_source: "primary"
  sources:
    - "Microsoft Windows Task Scheduler Documentation"
    - "MITRE ATT&CK T1053.005 - Scheduled Task"
    - "CVE-2018-8440 Task Scheduler ALPC Privilege Escalation"
  search_keywords:
    - "Task Scheduler"
    - "schtasks"
    - "Windows scheduled task"
    - "task scheduler persistence"
    - "scheduled task privilege escalation"
    - "CVE-2018-8440"
    - "remote scheduled task"
    - "task scheduler malware"
  embedding_text: >-
    Windows Task Scheduler is a system service enabling automated execution of programs and
    scripts at specified times or event triggers. Tasks are managed via schtasks.exe, COM
    APIs, and PowerShell, stored as XML in System32\Tasks. It is one of the most abused
    persistence mechanisms, with attackers creating tasks to survive reboots, execute as
    SYSTEM for privilege escalation, and use remote task creation via RPC for lateral
    movement. The service has had privilege escalation vulnerabilities (CVE-2018-8440 ALPC).
    Security teams should monitor task creation events (Event ID 4698), audit existing
    scheduled tasks regularly, restrict remote task creation, and detect tasks running
    from suspicious paths or with SYSTEM context for non-administrative operations.
